name: Laravel CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le projet
        uses: actions/checkout@v3

      - name: 🐘 Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: 📦 Installer Composer
        run: composer install --no-progress --prefer-dist

      - name: ⚙️ Configurer Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: 🧪 Lancer les tests
        run: php artisan test